<?php
session_start();
$enrollment=$_GET['enrollment'];
$con=mysqli_connect('localhost','root','123456789');
mysqli_select_db($con,'erp');
$query='select * from studentdata where enrollment="'.$enrollment.'"';
$res=mysqli_query($con,$query);
$array=mysqli_fetch_array($res);
echo '<br/>';
echo '<table align="center" style="border:1px solid red;align:center" cellpadding="3px">';
echo '<tr>';
echo '<td><label>Enrollment No.</label></td>';
echo '<td><input type="text" name="enrollment" value="'.$array['enrollment'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Name</label></td>';
echo '<td><input type="text" name="name" value="'.$array['name'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Course</label></td>';
echo '<td><input type="text" name="course" value="'.$array['course'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Year</label></td>';
echo '<td><input type="number" name="year" value="'.$array['year'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Branch</label></td>';
echo '<td><input type="text" name="branch" value="'.$array['branch'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Semester</label></td>';
echo '<td><input type="number" name="semester" value="'.$array['semester'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Mobile No.</label></td>';
echo '<td><input type="text" name="mobile" value="'.$array['mobile'].'" /></td>';
echo '</tr>';
echo '<tr>';
echo '<td><label>Email ID</label></td>';
echo '<td><input type="text" name="email" value="'.$array['email'].'" /></td>';
echo '</tr>';
echo '</table>';
echo '<br/>';
echo '<input type="submit" value="Update" style="width:500px;font-size:18px"/><br/><br/><br/>';
?>