<?php
session_start();
$year=$_POST['year'];
$branch=$_POST['branch'];
$semester=$_POST['semester'];
$tablename=($year.$branch.$semester);
$con=mysqli_connect('localhost','root','123456789');
mysqli_select_db($con,'erp');
$query='delete table '.$tablename;
mysqli_query($con,$query);
$query='create table '.$tablename.'(day__lectures varchar(15),lec1 varchar(15),lec2 varchar(15),lec3 varchar(15),lec4 varchar(15),lec5 varchar(15),lec6 varchar(15),lec7 varchar(15))';
mysqli_query($con,$query);
$M1=$_POST['M1'];
$M2=$_POST['M2'];
$M3=$_POST['M3'];
$M4=$_POST['M4'];
$M5=$_POST['M5'];
$M6=$_POST['M6'];
$M7=$_POST['M7'];
$query='insert into '.$tablename.' values ("Monday","'.$M1.'","'.$M2.'","'.$M3.'","'.$M4.'","'.$M5.'","'.$M6.'","'.$M7.'")';
mysqli_query($con,$query);
$T1=$_POST['T1'];
$T2=$_POST['T2'];
$T3=$_POST['T3'];
$T4=$_POST['T4'];
$T5=$_POST['T5'];
$T6=$_POST['T6'];
$T7=$_POST['T7'];
$query='insert into '.$tablename.' values ("Tuesday","'.$T1.'","'.$T2.'","'.$T3.'","'.$T4.'","'.$T5.'","'.$T6.'","'.$T7.'")';
mysqli_query($con,$query);
$W1=$_POST['W1'];
$W2=$_POST['W2'];
$W3=$_POST['W3'];
$W4=$_POST['W4'];
$W5=$_POST['W5'];
$W6=$_POST['W6'];
$W7=$_POST['W7'];
$query='insert into '.$tablename.' values ("Wednesday","'.$W1.'","'.$W2.'","'.$W3.'","'.$W4.'","'.$W5.'","'.$W6.'","'.$W7.'")';
mysqli_query($con,$query);
$Th1=$_POST['Th1'];
$Th2=$_POST['Th2'];
$Th3=$_POST['Th3'];
$Th4=$_POST['Th4'];
$Th5=$_POST['Th5'];
$Th6=$_POST['Th6'];
$Th7=$_POST['Th7'];
$query='insert into '.$tablename.' values ("Thursday","'.$Th1.'","'.$Th2.'","'.$Th3.'","'.$Th4.'","'.$Th5.'","'.$Th6.'","'.$Th7.'")';
mysqli_query($con,$query);
$F1=$_POST['F1'];
$F2=$_POST['F2'];
$F3=$_POST['F3'];
$F4=$_POST['F4'];
$F5=$_POST['F5'];
$F6=$_POST['F6'];
$F7=$_POST['F7'];
$query='insert into '.$tablename.' values ("Friday","'.$F1.'","'.$F2.'","'.$F3.'","'.$F4.'","'.$F5.'","'.$F6.'","'.$F7.'")';
mysqli_query($con,$query);
$S1=$_POST['S1'];
$S2=$_POST['S2'];
$S3=$_POST['S3'];
$S4=$_POST['S4'];
$S5=$_POST['S5'];
$S6=$_POST['S6'];
$S7=$_POST['S7'];
$query='insert into '.$tablename.' values ("Saturday","'.$S1.'","'.$S2.'","'.$S3.'","'.$S4.'","'.$S5.'","'.$S6.'","'.$S7.'")';
mysqli_query($con,$query);
header("location:http://localhost/E.R.P./Admin.php");
?>